CREATE TABLE IF NOT EXISTS datasets (
	id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	sentiment VARCHAR(255) NOT NULL,
	class VARCHAR(50) NOT NULL,
	expected_result VARCHAR(50) NOT NULL,
	prediction VARCHAR(255),
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS results (
	id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	class VARCHAR(50) NOT NULL,
	precision_value DECIMAL(5,2) NOT NULL,
	accuracy_value DECIMAL(5,2) NOT NULL,
	recall_value DECIMAL(5,2) NOT NULL,
	f_measure_value DECIMAL(5,2) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);
