CREATE TABLE IF NOT EXISTS tweets (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tweet TEXT NOT NULL,
	created_at TIMESTAMP,
	updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS datasets (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	sentiment TEXT NOT NULL,
	class VARCHAR(50) NOT NULL,
	expected_result TINYINT UNSIGNED,
	prediction_result TINYINT UNSIGNED,
	created_at TIMESTAMP,
	updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS results (
	id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	class VARCHAR(50) NOT NULL,
	precision_value DECIMAL(5, 2) NOT NULL,
	accuracy_value DECIMAL(5, 2) NOT NULL,
	recall_value DECIMAL(5, 2) NOT NULL,
	f_measure_value DECIMAL(5, 2) NOT NULL,
	created_at TIMESTAMP,
	updated_at TIMESTAMP
);

ALTER TABLE
	datasets
ADD
	COLUMN preprocessed TEXT;